package edu.kpi.lab.lab1.model;

public enum SyntaxType {
  START, FINISH, FIRST_OPERAND, OPERAND, FUNCTION, FUNCTION_OPEN_BRACKET, FUNCTION_CLOSE_BRACKET, OPERATION_ADD_OR_MINUS, OPERATION_MULTIPLY_OR_DIVIDE, OPEN_BRACKET, CLOSE_BRACKET, ERROR
}
