package edu.kpi.lab.lab1.model;

public enum TokenType {
  INTEGER, DECIMAL, CONSTANT, FUNCTION, FUNCTION_OPEN_BRACKET, FUNCTION_CLOSE_BRACKET, OPERATION_ADD, OPERATION_MINUS, OPERATION_MULTIPLY, OPERATION_DIVIDE, OPEN_BRACKET, CLOSE_BRACKET, ERROR
}
